# Generated by Django 6.0.3 on 2026-05-20 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_social', '0003_notification_like_unique_like_notification_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='reciever',
            new_name='receiver',
        ),
    ]
